Script started on Wed 22 Nov 2017 04:38:13 PM PST
]0;aahussai@laguna:~/hw4[aahussai@laguna ~/hw4]$ m[K]0;aahussai@laguna:~/hw4[aahussai@laguna ~/hw4]$ make
gcc -ansi -Wall -c -std=c99 -DDEBUG -c PhotoLab.c -o PhotoLab_DEBUG.o
gcc  PhotoLab_DEBUG.o FileIO.o Test_DEBUG.o Image.o -L. -lFilter -o PhotoLabTest
gcc: Test_DEBUG.o: No such file or directory
make: *** [PhotoLabTest] Error 1
]0;aahussai@laguna:~/hw4[aahussai@laguna ~/hw4]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add Noise to an image
12: Sharpen an image
13: Posterize an image
14: Add Motion Blur to an image
15: crop an image
16: Resize an image
17: Brightness and Contrast
18: Watermark an image
19: AutoTest
20: EXIT
Please make your choice: 20  19
PhotoLab: Image.c:32: SetPixelR: Assertion `y < image->H' failed.
Abort (core dumped)
]0;aahussai@laguna:~/hw4[aahussai@laguna ~/hw4]$ valgrind --leak-check=full PhotoLabTest
valgrind: PhotoLabTest: command not found
]0;aahussai@laguna:~/hw4[aahussai@laguna ~/hw4]$ make clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm negative.ppm colorfilter.ppm edge.ppm vflipflip.ppm shuffle.ppm vmirror.ppm border.ppm noise.ppm sharpen.ppm posterize.ppm blur.ppm libFilter.a libFileIO.a
]0;aahussai@laguna:~/hw4[aahussai@laguna ~/hw4]$ exit
exit

Script done on Wed 22 Nov 2017 04:39:27 PM PST
